### ISSUE TITLE
One weird AppImage sort

### ISSUE THREAD

**Issue by fov95** [Tempest20/sorti-py#2]
I tried the script on my dl folder and one thing was off.

I have the files

> obs-studio-plus-25.0.8-x86_64.AppImage
> yuzu-20220223-aa8ceb112.AppImage

obs was moved to "AppImage" folder as expected but yuzu was moved into a "yuzu" folder.

As I am writing this I moved both files again out of their folders, removed the folders and ran the command again but this time both where moved into an "AppImage" folder.
So I can't replicate it again.
I am leaving this anyways if something similar happens again for someone else. 

One more thing.
I have jpg & jpeg files in different folders. I would probably put those in the same folder. Just a suggestion.

**Comment by bajramidamir** [comment]
Code has been significantly improved since the first commit, so there shouldn't be any more similar issues.
