### ISSUE TITLE
Issue: does not work in large folders

### ISSUE THREAD

**Issue by firinael** [Tempest20/sorti-py#6]
Just tried using this tool in my "random stuff" folder with a bunch of pdf files, svg files, a few mp3s, etc. Seems like the script just picked up the first few files and stopped, since folders were created and some files were moved, but not all.

This is on Windows, using Python 3.10.2, and the most recent release as of 30/03/2022, 17:03 GMT-3.

**Comment by bajramidamir** [comment]
Just tested it on a huge folder full of .cpp, .pdf, .docx, .py and tons more extensions (even some files with no extensions at all)
All of it worked fine. I can't seem to be able to replicate your issue, so I'm not sure what it's about. 
The only thing that comes to mind is that maybe you had files with conflicting names, so the program crashed. I fixed that issue on both the CLI and the GUI version. Try testing it again and reporting if the same thing happens.
